import { useEffect, useMemo, useState } from 'react';
import './App.css';
import { checkoutSubscription, getDocuments, getSubscription, login, logout as apiLogout, register, uploadDocument } from './api';
import AITutorPage from './components/ai-tutor/AITutorPage';

const SUBJECTS = [{ id: 'CS', name: 'Khoa học máy tính' }, { id: 'OS', name: 'Hệ điều hành' }, { id: 'SEC', name: 'An toàn thông tin' }, { id: 'WEB', name: 'Lập trình Web' }];
const PLANS = { free: { name: 'Miễn phí', price: '0đ', usage: '20 lượt hỏi / tháng', items: ['Kho học liệu cá nhân', '20 lượt hỏi Nova / tháng', 'Theo dõi tiến độ'] }, plus: { name: 'Plus', price: '79.000đ', usage: '300 lượt hỏi / tháng', items: ['300 lượt hỏi Nova / tháng', 'Tải tài liệu để hỏi', 'Quiz và tóm tắt'] }, pro: { name: 'Pro', price: '149.000đ', usage: '1.200 lượt hỏi / tháng', items: ['1.200 lượt hỏi Nova / tháng', 'Ngữ cảnh tài liệu dài hơn', 'Ưu tiên tính năng mới'] } };
const INITIAL_PROGRESS = [{ id: 1, title: 'Cấu trúc dữ liệu', subject: 'CS', percent: 68, minutes: 105 }, { id: 2, title: 'Quy trình Linux', subject: 'OS', percent: 42, minutes: 64 }, { id: 3, title: 'Web security cơ bản', subject: 'SEC', percent: 30, minutes: 45 }];
function Modal({ title, children, onClose }) { const isCheckout = title === 'Xác nhận thay đổi gói'; return <div className="modal-backdrop" onMouseDown={onClose}><section className={`modal ${isCheckout ? 'checkout-modal' : ''}`} role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><header><h2>{isCheckout ? 'Thanh toán & thay đổi gói' : title}</h2><button aria-label="Đóng" onClick={onClose}>×</button></header>{isCheckout && <div className="checkout-banner"><strong>Thanh toán minh bạch</strong><span>Nâng gói áp dụng ngay ở môi trường demo · Hạ gói chỉ chuyển vào cuối chu kỳ.</span><div><b>Chu kỳ tháng</b><b>Không phí ẩn</b><b>Không lưu số thẻ</b></div></div>}{children}</section></div>; }

export default function App() {
  const [view, setView] = useState('home'); const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('studyhub-user')); } catch { return null; } });
  const [documents, setDocuments] = useState([]); const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [progress, setProgress] = useState(INITIAL_PROGRESS); const [modal, setModal] = useState(null); const [authMode, setAuthMode] = useState('login'); const [toast, setToast] = useState(''); const [selectedDocument, setSelectedDocument] = useState(null);
  const [subscription, setSubscription] = useState(() => { try { return JSON.parse(localStorage.getItem('studyhub-subscription')) || { plan: 'free', status: 'active' }; } catch { return { plan: 'free', status: 'active' }; } }); const [pendingPlan, setPendingPlan] = useState(null); const [billingCycle] = useState('month'); const [paymentMethod, setPaymentMethod] = useState('card');
  const average = Math.round(progress.reduce((total, item) => total + item.percent, 0) / progress.length); const filteredDocs = useMemo(() => documents.filter((doc) => (filter === 'all' || doc.subject?.code === filter) && `${doc.title} ${doc.description || ''}`.toLowerCase().includes(search.toLowerCase())), [documents, filter, search]);
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 3200); }; const saveUser = (next) => { setUser(next); next ? localStorage.setItem('studyhub-user', JSON.stringify(next)) : localStorage.removeItem('studyhub-user'); }; const saveSubscription = (next) => { setSubscription(next); localStorage.setItem('studyhub-subscription', JSON.stringify(next)); };
  const loadDocuments = async () => { try { setDocuments(await getDocuments()); } catch { setDocuments([]); } }; const loadSubscription = async () => { try { saveSubscription(await getSubscription()); } catch { /* Retain local display state when offline. */ } }; useEffect(() => { if (!user) return undefined; const timer = window.setTimeout(() => { void loadDocuments(); void loadSubscription(); }, 0); return () => window.clearTimeout(timer); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);
  const requireLogin = () => { if (user) return false; setAuthMode('login'); setModal('auth'); notify('Đăng nhập để dùng tính năng cá nhân.'); return true; }; const go = (next) => { if (next === 'tutor' && requireLogin()) return; setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const signOut = async () => { try { await apiLogout(); } catch { /* Always clear the local session. */ } saveUser(null); setDocuments([]); setView('home'); notify('Đã đăng xuất và xóa phiên làm việc trên trình duyệt.'); };
  const submitAuth = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = authMode === 'login' ? await login(data.get('email'), data.get('password')) : await register(data.get('name'), data.get('email'), data.get('password')); saveUser(result.user || result); setModal(null); notify(authMode === 'login' ? 'Đăng nhập thành công.' : 'Tạo tài khoản thành công.'); } catch (error) { notify(`Không thể thực hiện: ${error.message}`); } };
  const submitUpload = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get('file'); if (!file?.name) return notify('Hãy chọn tài liệu trước.'); try { await uploadDocument({ file, title: data.get('title') || file.name.replace(/\.[^.]+$/, ''), description: data.get('description'), subjectCode: data.get('subject') }); setModal(null); await loadDocuments(); notify('Đã tải tài liệu vào kho học liệu.'); } catch (error) { notify(`Upload thất bại: ${error.message}`); } };
  const requestPlan = (plan) => { if (requireLogin() || plan === subscription.plan) return; setPendingPlan(plan); setPaymentMethod('card'); setModal('plan'); }; const confirmPlan = async () => { try { const result = await checkoutSubscription({ plan: pendingPlan, billingCycle, paymentMethod }); saveSubscription(result); setModal(null); notify(result.change_type === 'downgrade_scheduled' ? 'Đã lên lịch hạ gói vào cuối chu kỳ.' : `Đã kích hoạt gói ${PLANS[pendingPlan].name} trong môi trường demo.`); } catch (error) { notify(`Không thể xử lý yêu cầu: ${error.message}`); } };
  return <div className="studyhub-app"><header className="topbar"><button className="brand-wrap" onClick={() => go('home')}><span className="brand-mark">S</span><span className="brand-text">Study<span>Hub</span></span></button><nav className="nav-menu">{[['home', 'Trang chủ'], ['library', 'Kho học liệu'], ['dashboard', 'Tiến độ'], ['tutor', 'AI Tutor'], ['pricing', 'Gói học']].map(([id, label]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => go(id)}>{label}</button>)}</nav><div className="auth-box">{user ? <><button className="user-pill" onClick={() => setModal('account')}><span className="user-avatar">{user.name?.[0]?.toUpperCase() || 'U'}</span>{user.name}</button><button className="btn btn-ghost" onClick={signOut}>Đăng xuất</button></> : <><button className="btn btn-ghost" onClick={() => { setAuthMode('login'); setModal('auth'); }}>Đăng nhập</button><button className="btn btn-primary" onClick={() => { setAuthMode('register'); setModal('auth'); }}>Bắt đầu</button></>}</div></header><main className="main-shell">
    {view === 'home' && <><section className="hero-section"><div className="hero-copy"><span className="eyebrow">STUDYHUB · HỌC CÁ NHÂN CÓ ĐỊNH HƯỚNG</span><h1>Học sâu hơn.<br /><span>Tiến bộ rõ hơn.</span></h1><p>Tổ chức tài liệu, theo dõi tiến độ và trao đổi với Nova — AI Tutor luôn đặt bài học của bạn làm trung tâm.</p><div className="hero-actions"><button className="btn btn-primary large" onClick={() => go('tutor')}>Hỏi Nova AI Tutor</button><button className="btn btn-outline large" onClick={() => go('library')}>Mở kho học liệu</button></div></div><div className="hero-visual"><div className="progress-card"><span className="eyebrow">NHỊP HỌC TUẦN NÀY</span><div className="big-number">{average}<span>%</span></div><div className="progress-bar"><span style={{ width: `${average}%` }} /></div><div className="mini-grid"><div className="mini-item"><strong>{documents.length}</strong><small>tài liệu</small></div><div className="mini-item"><strong>{progress.length}</strong><small>mục đang học</small></div></div></div></div></section><section className="content-section"><span className="eyebrow">WORKFLOW CÁ NHÂN</span><h2>Một nhịp học gọn gàng.</h2><div className="workflow-grid">{[['01', 'Lưu học liệu', 'Đưa tài liệu cần học vào một kho riêng.', 'library'], ['02', 'Theo dõi nhịp học', 'Cập nhật tiến độ từng chủ đề quan trọng.', 'dashboard'], ['03', 'Hỏi Nova', 'Nhận giải thích, gợi ý, tóm tắt hoặc quiz.', 'tutor']].map(([num, title, detail, target]) => <article className="workflow-card" key={num}><span className="step-tag">{num}</span><h3>{title}</h3><p>{detail}</p><button className="text-link" onClick={() => go(target)}>Mở tính năng →</button></article>)}</div></section></>}
    {view === 'library' && <section className="page"><div className="page-header"><div><span className="eyebrow">KHO CÁ NHÂN</span><h2>Học liệu của bạn</h2><p className="muted">Tải lên và dùng trực tiếp trong AI Tutor.</p></div><button className="btn btn-primary" onClick={() => !requireLogin() && setModal('upload')}>＋ Tải tài liệu</button></div><div className="library-tools"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm tài liệu…" /><div className="filter-tabs"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>Tất cả</button>{SUBJECTS.map((subject) => <button className={filter === subject.id ? 'active' : ''} onClick={() => setFilter(subject.id)} key={subject.id}>{subject.id}</button>)}</div></div><div className="document-grid">{filteredDocs.map((doc) => <article className="document-card" key={doc.id}><span>{doc.subject?.code || 'DOC'}</span><h3>{doc.title}</h3><p>{doc.description || 'Tài liệu chưa có mô tả.'}</p><button className="text-link" onClick={() => { setSelectedDocument(doc); go('tutor'); }}>Hỏi Nova về tài liệu →</button></article>)}{!filteredDocs.length && <div className="empty-state">{user ? 'Chưa có tài liệu phù hợp. Hãy tải tài liệu đầu tiên.' : 'Đăng nhập để xem kho học liệu cá nhân.'}</div>}</div></section>}
    {view === 'dashboard' && <section className="page"><div className="page-header"><div><span className="eyebrow">TIẾN ĐỘ CÁ NHÂN</span><h2>{user ? `Chào ${user.name}` : 'Tiến độ học tập'}</h2><p className="muted">Không còn không gian học nhóm — mọi dữ liệu ở đây là của riêng bạn.</p></div><button className="btn btn-primary" onClick={() => go('tutor')}>Mở Nova AI Tutor</button></div><div className="stats-grid"><div className="stat-box red"><span>Tiến độ</span><strong>{average}%</strong><small>trung bình các mục</small></div><div className="stat-box blue"><span>Thời gian học</span><strong>{Math.floor(progress.reduce((sum, item) => sum + item.minutes, 0) / 60)}h</strong><small>đã ghi nhận</small></div><div className="stat-box dark"><span>Tài liệu</span><strong>{documents.length}</strong><small>trong kho cá nhân</small></div></div><section className="panel-card progress-panel"><div className="panel-head"><h3>Tiến độ của bạn</h3><span className="panel-chip">{progress.length} mục</span></div><div className="progress-list">{progress.map((item) => <div className="progress-row" key={item.id}><div className="progress-info"><strong>{item.title}</strong><small>{item.subject} · {item.minutes} phút học</small></div><div className="progress-control"><input type="range" min="0" max="100" value={item.percent} onChange={(e) => setProgress((all) => all.map((current) => current.id === item.id ? { ...current, percent: +e.target.value, minutes: Math.max(current.minutes, Math.round(+e.target.value * 1.2)) } : current))} /><span>{item.percent}%</span></div></div>)}</div></section></section>}
    {view === 'tutor' && <AITutorPage selectedDocument={selectedDocument} />}
    {view === 'pricing' && <section className="pricing-page"><div className="page-header center-header"><div><span className="eyebrow">NOVA MEMBERSHIP</span><h2>Chọn dung lượng học phù hợp.</h2><p className="muted">Các gói dùng chung trải nghiệm cốt lõi; khác nhau ở hạn mức AI và độ dài ngữ cảnh. Giao diện chỉ ghi nhận yêu cầu, thanh toán thật do Backend xử lý.</p></div></div><div className="price-grid">{Object.entries(PLANS).map(([id, plan]) => <article className={`price-card ${id === 'plus' ? 'featured' : ''} ${subscription.plan === id ? 'active' : ''}`} key={id}><span className="plan-badge">{plan.name}</span><h3>{plan.name}</h3><div className="price-line">{plan.price}<span>{id === 'free' ? '' : ' / tháng'}</span></div><strong className="plan-usage">{plan.usage}</strong><ul>{plan.items.map((item) => <li key={item}>{item}</li>)}</ul><button className={`btn full ${subscription.plan === id ? 'btn-ghost' : id === 'free' ? 'btn-outline' : 'btn-primary'}`} disabled={subscription.plan === id} onClick={() => requestPlan(id)}>{subscription.plan === id ? 'Gói hiện tại' : id === 'free' ? 'Chuyển về Miễn phí' : `Chọn ${plan.name}`}</button></article>)}</div>{user && <section className="subscription-panel"><div><span className="eyebrow">TRẠNG THÁI GÓI</span><h3>{PLANS[subscription.plan].name} · {PLANS[subscription.plan].usage}</h3><p>{subscription.status === 'scheduled_change' ? 'Thay đổi gói đã được lên lịch cho cuối chu kỳ hiện tại.' : 'Gói đang hoạt động. Mọi thay đổi đều cần xác nhận trước khi áp dụng.'}</p></div><button className="btn btn-ghost" disabled={subscription.plan === 'free'} onClick={() => { saveSubscription({ plan: subscription.plan, status: 'scheduled_change' }); notify('Đã lên lịch hủy gia hạn vào cuối chu kỳ.'); }}>Hủy gia hạn</button></section>}</section>}
  </main>{modal === 'auth' && <Modal title={authMode === 'login' ? 'Đăng nhập StudyHub' : 'Tạo tài khoản'} onClose={() => setModal(null)}><form className="auth-form" onSubmit={submitAuth}>{authMode === 'register' && <label>Họ tên<input name="name" required /></label>}<label>Email<input name="email" type="email" required /></label><label>Mật khẩu<input name="password" type="password" minLength="6" required /></label><button className="btn btn-primary full">{authMode === 'login' ? 'Đăng nhập' : 'Tạo tài khoản'}</button><button type="button" className="text-link" onClick={() => setAuthMode(authMode === 'login' ? 'register' : 'login')}>{authMode === 'login' ? 'Chưa có tài khoản? Đăng ký' : 'Đã có tài khoản? Đăng nhập'}</button></form></Modal>}{modal === 'upload' && <Modal title="Tải tài liệu" onClose={() => setModal(null)}><form className="auth-form" onSubmit={submitUpload}><label>Tệp<input name="file" type="file" required /></label><label>Tiêu đề<input name="title" /></label><label>Môn học<select name="subject">{SUBJECTS.map((subject) => <option value={subject.id} key={subject.id}>{subject.id} · {subject.name}</option>)}</select></label><label>Mô tả<textarea name="description" rows="3" /></label><button className="btn btn-primary full">Tải lên</button></form></Modal>}{modal === 'plan' && <Modal title="Xác nhận thay đổi gói" onClose={() => setModal(null)}><p>Bạn đang yêu cầu chuyển từ <strong>{PLANS[subscription.plan].name}</strong> sang <strong>{PLANS[pendingPlan].name}</strong>.</p><p className="muted">Việc thanh toán thực tế chưa được khởi tạo tại giao diện này. Backend sẽ xử lý an toàn khi tích hợp cổng thanh toán.</p><button className="btn btn-primary full" onClick={confirmPlan}>Xác nhận yêu cầu</button></Modal>}{modal === 'account' && <Modal title="Tài khoản" onClose={() => setModal(null)}><p><strong>{user?.name}</strong><br />{user?.email}</p><button className="btn btn-outline full" onClick={() => { setModal(null); signOut(); }}>Đăng xuất khỏi thiết bị này</button></Modal>}{toast && <div className="toast">{toast}</div>}</div>;
}
