spring.application.name=backend
server.port=5000
# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:h2:file:./data/studyhub;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Cấu hình JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# RẤT QUAN TRỌNG: Tự động tạo/cập nhật bảng dựa trên Entity
spring.jpa.hibernate.ddl-auto=update
# Mo rong gioi han dung luong file upload (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
