spring.application.name=backend
# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/studyhub
spring.datasource.username=postgres
spring.datasource.password=thaituanvu06@
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# RẤT QUAN TRỌNG: Tự động tạo/cập nhật bảng dựa trên Entity
spring.jpa.hibernate.ddl-auto=update
# Mo rong gioi han dung luong file upload (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB