import { useMemo, useReducer, useState } from "react";
import { ArrowLeftIcon, ArrowRightIcon, BookOpenIcon, ClockIcon, DocumentPlusIcon, PlusIcon, SparklesIcon } from "@heroicons/react/24/outline";
import { getDocumentContent } from "../../api";
import "./roadmap-hub.css";
import MaterialList from "./MaterialList";
import MaterialUploader from "./MaterialUploader";
import RoadmapCard from "./RoadmapCard";
import TimelineStepCard from "./TimelineStepCard";
import TypeSelector from "./TypeSelector";
import WizardStepper from "./WizardStepper";
import { calcRoadmapProgress, calcStepProgress, calcStreak, deriveSteps, formatHours, syncStepStatuses } from "./roadmap.logic";
import { useStudySessions } from "./useStudySessions";
import { useStudyTimer } from "./useStudyTimer";
import type { Material, Roadmap, RoadmapStep, RoadmapType, StudySession } from "./roadmap.types";

const GOALS = ["Nắm kiến thức", "Chuẩn bị kỳ thi", "Làm bài tập", "Làm dự án", "Ứng dụng vào công việc"];
const EMPTY = { step: 0, type: null as RoadmapType | null, selected: [] as string[], subject: "", query: "", upload: false, goals: [] as string[], weeks: "", hoursPerDay: "", daysPerWeek: "", error: "" };
function reducer(state: typeof EMPTY, action: any) {
  if (action.type === "reset") return { ...EMPTY };
  if (action.type === "toggle") return { ...state, selected: state.type === "document" ? [action.id] : state.selected.includes(action.id) ? state.selected.filter((id) => id !== action.id) : [...state.selected, action.id], error: "" };
  if (action.type === "goal") return { ...state, goals: state.goals.includes(action.value) ? state.goals.filter((item) => item !== action.value) : [...state.goals, action.value], error: "" };
  return { ...state, [action.key]: action.value, error: action.key === "error" ? action.value : "" };
}
const toMaterial = (document: any): Material | null => {
  const name = String(document?.original_filename || document?.filename || document?.title || ""); const type = name.split(".").pop()?.toLowerCase();
  if (!name || !["pdf", "docx", "pptx", "txt"].includes(type || "")) return null;
  return { id: `library-${document.id}`, name, type: type as Material["type"], chapters: Number(document.page_count || 1), subject: document.subject_name || "Chưa phân loại", status: document.status === "failed" ? "failed" : "ready" };
};

export default function RoadmapHub({ documents = [], user, onOpenDocument, onTakeQuiz, onAskNova }: any) {
  const userId = String(user?.id || user?.email || "guest");
  const { data, setData, addSession, updateSession, deleteSession } = useStudySessions(userId);
  const [library, setLibrary] = useState<Material[]>(() => documents.map(toMaterial).filter(Boolean) as Material[]);
  const [activeId, setActiveId] = useState<string | null>(null); const [selectedStepId, setSelectedStepId] = useState<string | null>(null);
  const [wizardOpen, setWizardOpen] = useState(false); const [creating, setCreating] = useState(false); const [manualOpen, setManualOpen] = useState(false); const [toast, setToast] = useState("");
  const [wizard, dispatch] = useReducer(reducer, EMPTY); const [manual, setManual] = useState({ stepId: "", date: new Date().toLocaleDateString("en-CA"), hours: "", minutes: "" });
  const timer = useStudyTimer(addSession);
  const roadmaps = useMemo(() => data.roadmaps.map((roadmap: Roadmap) => { const steps = syncStepStatuses(roadmap.steps, data.sessions); const totals = calcRoadmapProgress({ ...roadmap, steps }, data.sessions); return { ...roadmap, steps, ...totals, status: totals.percent >= 100 ? "completed" : "in_progress" }; }), [data]);
  const active = roadmaps.find((item: Roadmap) => item.id === activeId) || null; const selectedStep = active?.steps.find((item: RoadmapStep) => item.id === selectedStepId) || null;
  const allMaterials = useMemo(() => [...documents.map(toMaterial).filter(Boolean) as Material[], ...library].filter((item, index, rows) => rows.findIndex((row) => row.id === item.id) === index), [documents, library]);
  const ready = allMaterials.filter((item) => item.status === "ready"); const subjects = [...new Set(ready.map((item) => item.subject))];
  const choices = ready.filter((item) => (!wizard.subject || item.subject === wizard.subject) && item.name.toLocaleLowerCase("vi").includes(wizard.query.toLocaleLowerCase("vi")));
  const totals = active ? calcRoadmapProgress(active, data.sessions) : null; const streak = calcStreak(data.sessions);
  const addMaterial = (material: Material) => { setLibrary((current) => current.some((item) => item.id === material.id) ? current : [...current, material]); dispatch({ type: "toggle", id: material.id }); };
  const validate = () => {
    if (wizard.step === 0 && !wizard.type) return "Hãy chọn loại lộ trình.";
    if (wizard.step === 1 && wizard.type === "document" && wizard.selected.length !== 1) return "Hãy chọn một tài liệu đã sẵn sàng.";
    if (wizard.step === 1 && wizard.type === "subject" && (!wizard.subject || !wizard.selected.length)) return "Hãy chọn môn học và ít nhất một tài liệu đã sẵn sàng.";
    if (wizard.step === 2 && !wizard.goals.length) return "Hãy chọn ít nhất một mục tiêu học.";
    if (wizard.step === 2 && (!Number.isInteger(Number(wizard.weeks)) || Number(wizard.weeks) < 1 || Number(wizard.weeks) >= 50)) return "Số tuần phải là số nguyên từ 1 đến 49.";
    if (wizard.step === 2 && (!Number.isInteger(Number(wizard.hoursPerDay)) || Number(wizard.hoursPerDay) < 1 || Number(wizard.hoursPerDay) > 24)) return "Giờ học mỗi ngày phải là số nguyên từ 1 đến 24.";
    if (wizard.step === 2 && (!Number.isInteger(Number(wizard.daysPerWeek)) || Number(wizard.daysPerWeek) < 1 || Number(wizard.daysPerWeek) > 7)) return "Số ngày học mỗi tuần phải là số nguyên từ 1 đến 7.";
    return "";
  };
  const next = async () => {
    const error = validate(); if (error) { dispatch({ key: "error", value: error }); return; }
    if (wizard.step < 2) { dispatch({ key: "step", value: wizard.step + 1 }); return; }
    setCreating(true); const sources = ready.filter((item) => wizard.selected.includes(item.id)); const contents: Record<string, string> = {};
    await Promise.all(sources.map(async (source) => { try { const result = await getDocumentContent(source.id.replace("library-", "")); contents[source.id] = result.content || ""; } catch { contents[source.id] = ""; } }));
    const totalHours = Number(wizard.weeks) * Number(wizard.hoursPerDay) * Number(wizard.daysPerWeek); const steps = deriveSteps(sources, contents, totalHours);
    const roadmap: Roadmap = { id: crypto.randomUUID(), type: wizard.type!, title: wizard.type === "document" ? sources[0].name.replace(/\.[^.]+$/, "") : wizard.subject, subject: wizard.subject || sources[0]?.subject, status: "in_progress", totalHours, hoursDone: 0, weeks: Number(wizard.weeks), daysPerWeek: Number(wizard.daysPerWeek), hoursPerDay: Number(wizard.hoursPerDay), goals: wizard.goals, sources, steps };
    setData((current: any) => ({ ...current, roadmaps: [roadmap, ...current.roadmaps] })); setCreating(false); setWizardOpen(false); setActiveId(roadmap.id);
  };
  const complete = (step: RoadmapStep) => {
    if (calcStepProgress(step, data.sessions) < 50 && !window.confirm(`Bạn mới học ${formatHours(step.hoursDone)} / ${formatHours(step.durationHours)}. Vẫn đánh dấu hoàn thành?`)) return;
    setData((current: any) => ({ ...current, roadmaps: current.roadmaps.map((roadmap: Roadmap) => roadmap.id !== active?.id ? roadmap : { ...roadmap, steps: roadmap.steps.map((item) => item.id === step.id ? { ...item, manuallyCompleted: true } : item) }) }));
    setToast("Đã hoàn thành chủ đề. Hoàn tác"); window.setTimeout(() => setToast(""), 5000);
  };
  const undo = () => { if (!selectedStep) return; setData((current: any) => ({ ...current, roadmaps: current.roadmaps.map((roadmap: Roadmap) => roadmap.id !== active?.id ? roadmap : { ...roadmap, steps: roadmap.steps.map((item) => item.id === selectedStep.id ? { ...item, manuallyCompleted: false } : item) }) })); setToast(""); };
  const saveManual = () => { const minutes = Math.round(Number(manual.hours || 0) * 60 + Number(manual.minutes || 0)); if (!manual.stepId || minutes <= 0 || minutes > 1440) return; const startedAt = new Date(`${manual.date}T12:00:00`).toISOString(); addSession({ roadmapId: active.id, stepId: manual.stepId, startedAt, endedAt: startedAt, minutes, source: "manual" }); setManualOpen(false); };
  const sourceDocument = (step: RoadmapStep) => documents.find((doc: any) => step.sources.some((source) => source.materialId === `library-${doc.id}`));

  if (activeId && !active) return <main className="rm-page"><section className="rm-empty"><h1>Không tìm thấy lộ trình</h1><button className="btn btn-primary" onClick={() => setActiveId(null)}>Quay lại</button></section></main>;
  if (active) return <main className="rm-page"><button className="rm-back" onClick={() => { setActiveId(null); setSelectedStepId(null); }}><ArrowLeftIcon />Quay lại lộ trình học</button>
    <header className="rm-detail-header"><div><span className={`rm-status is-${active.status}`}>{active.status === "completed" ? "Hoàn thành" : "Đang học"}</span><h1>{active.title}</h1><p>{active.sources.length} tài liệu · {streak} ngày liên tiếp</p></div><button className="btn btn-outline" onClick={onAskNova}><SparklesIcon />Điều chỉnh với Nova</button></header>
    <section className="rm-overview-card"><div className="rm-overview-progress"><strong>{Math.round(totals!.percent)}%</strong><span>{formatHours(totals!.hoursDone)} / {formatHours(totals!.totalHours)}</span><progress max="100" value={totals!.percent} /></div><dl><div><dt>Đã học</dt><dd>{formatHours(totals!.hoursDone)}</dd></div><div><dt>Còn khoảng</dt><dd>{formatHours(totals!.remainingHours)}</dd></div><div><dt>Chủ đề</dt><dd>{active.steps.filter((step) => step.status === "completed").length}/{active.steps.length}</dd></div></dl><button className="btn btn-outline" onClick={() => setManualOpen(true)}>Ghi nhận giờ học</button></section>
    <section className="rm-detail-grid"><div><h2>Hành trình học tập</h2><div className="rm-timeline">{active.steps.map((step) => <TimelineStepCard key={step.id} step={step} type={active.type} materials={active.sources} onOpen={(item) => setSelectedStepId(item.id)} />)}</div></div><aside className="rm-nova-card"><ClockIcon /><h2>Lịch sử học</h2>{data.sessions.filter((item: StudySession) => item.roadmapId === active.id).length ? data.sessions.filter((item: StudySession) => item.roadmapId === active.id).slice().reverse().map((item: StudySession) => <div className="rm-history" key={item.id}><span>{new Date(item.startedAt).toLocaleDateString("vi-VN")} · {active.steps.find((step) => step.id === item.stepId)?.title}</span><strong>{formatHours(item.minutes / 60)}</strong><button onClick={() => { const value = window.prompt("Số phút", String(item.minutes)); if (value && Number(value) > 0 && Number(value) <= 1440) updateSession({ ...item, minutes: Number(value) }); }}>Sửa</button><button onClick={() => deleteSession(item.id)}>Xoá</button></div>) : <p>Chưa có phiên học nào.</p>}</aside></section>
    {selectedStep && <div className="rm-drawer-layer"><aside className="rm-drawer" role="dialog" aria-label={selectedStep.title}><header><h2>{selectedStep.title}</h2><button className="rm-icon-button" onClick={() => setSelectedStepId(null)}>×</button></header><div className="rm-progress-copy"><strong>{formatHours(selectedStep.hoursDone)} / {formatHours(selectedStep.durationHours)}</strong><span>{Math.round(calcStepProgress(selectedStep, data.sessions))}%</span></div><progress max="100" value={calcStepProgress(selectedStep, data.sessions)} /><div className="rm-timer"><strong>{new Date(timer.seconds * 1000).toISOString().slice(11, 19)}</strong>{timer.running ? <button className="btn btn-outline" onClick={timer.pause}>Tạm dừng</button> : <button className="btn btn-primary" onClick={timer.start}>Học nội dung</button>}<button className="btn btn-outline" onClick={() => timer.finish({ roadmapId: active.id, stepId: selectedStep.id })}>Kết thúc</button></div><div className="rm-drawer-actions"><button className="btn btn-outline" onClick={() => { const doc = sourceDocument(selectedStep); if (doc) onOpenDocument?.(doc); }}>Mở tài liệu</button><button className="btn btn-outline" onClick={() => { const doc = sourceDocument(selectedStep); if (doc) onTakeQuiz?.(doc); }}>Làm Quiz</button><button className="btn btn-ghost" onClick={() => complete(selectedStep)}>Đánh dấu hoàn thành</button></div></aside></div>}
    {manualOpen && <div className="rm-modal-layer"><section className="rm-wizard" role="dialog" aria-label="Ghi nhận giờ học"><header><h2>Ghi nhận giờ học</h2><button className="rm-icon-button" onClick={() => setManualOpen(false)}>×</button></header><div className="rm-wizard-body rm-time-grid"><label>Chủ đề<select value={manual.stepId} onChange={(event) => setManual({ ...manual, stepId: event.target.value })}><option value="">Chọn chủ đề</option>{active.steps.map((step) => <option key={step.id} value={step.id}>{step.title}</option>)}</select></label><label>Ngày<input type="date" value={manual.date} onChange={(event) => setManual({ ...manual, date: event.target.value })} /></label><label>Giờ<input type="number" min="0" max="24" value={manual.hours} onChange={(event) => setManual({ ...manual, hours: event.target.value })} /></label><label>Phút<input type="number" min="0" max="59" value={manual.minutes} onChange={(event) => setManual({ ...manual, minutes: event.target.value })} /></label></div><footer><button className="btn btn-primary" onClick={saveManual}>Lưu</button></footer></section></div>}{toast && <button className="rm-toast" onClick={undo}>{toast}</button>}
    {active.status === "completed" && <section className="rm-empty"><SparklesIcon /><h2>Chúc mừng! Bạn đã hoàn thành lộ trình</h2><p>Tổng thời gian đã học: {formatHours(totals!.hoursDone)}</p></section>}
  </main>;

  return <main className="rm-page"><header className="rm-list-header"><div><span className="rm-kicker">LỘ TRÌNH HỌC</span><h1>Học theo cách của bạn</h1><p>Mọi lộ trình được tạo từ tài liệu bạn tải lên.</p></div><button className="btn btn-primary" onClick={() => { dispatch({ type: "reset" }); setWizardOpen(true); }}><PlusIcon />Tạo lộ trình mới</button></header>
    {roadmaps.length ? <><section className="rm-quick-card"><div><span className="rm-kicker">LỘ TRÌNH HIỆN TẠI</span><h2>{roadmaps[0].title}</h2><p>{formatHours(roadmaps[0].hoursDone)} / {formatHours(roadmaps[0].totalHours)}</p></div><button className="btn btn-outline" onClick={() => setActiveId(roadmaps[0].id)}><BookOpenIcon />Tiếp tục học</button></section><section className="rm-card-grid">{roadmaps.map((roadmap: Roadmap) => <RoadmapCard key={roadmap.id} roadmap={roadmap} onOpen={(item) => setActiveId(item.id)} />)}</section></> : <section className="rm-empty"><DocumentPlusIcon /><h2>Bạn chưa có lộ trình nào</h2><p>Upload tài liệu để Nova tạo lộ trình đầu tiên.</p><button className="btn btn-primary" onClick={() => setWizardOpen(true)}>Tạo lộ trình mới</button></section>}
    {wizardOpen && <div className="rm-modal-layer"><section className="rm-wizard" role="dialog" aria-label="Tạo lộ trình mới">{creating ? <div className="rm-creating"><SparklesIcon /><h2>Nova đang đọc tài liệu và tạo lộ trình...</h2></div> : <><header><h2>Tạo lộ trình mới</h2><button className="rm-icon-button" onClick={() => setWizardOpen(false)}>×</button></header><WizardStepper current={wizard.step} /><div className="rm-wizard-body">
      {wizard.step === 0 && <TypeSelector value={wizard.type} onChange={(value) => dispatch({ key: "type", value })} />}
      {wizard.step === 1 && <><div className="rm-source-tabs"><button className={wizard.upload ? "is-active" : ""} onClick={() => dispatch({ key: "upload", value: true })}>Upload tài liệu mới</button><button className={!wizard.upload ? "is-active" : ""} onClick={() => dispatch({ key: "upload", value: false })}>Kho học liệu</button></div>{wizard.upload ? <MaterialUploader subject={wizard.subject} onComplete={addMaterial} /> : <>{wizard.type === "subject" && <label>Môn học<select value={wizard.subject} onChange={(event) => dispatch({ key: "subject", value: event.target.value })}><option value="">Chọn môn học</option>{subjects.map((name) => <option key={name}>{name}</option>)}</select></label>}{ready.length ? <MaterialList materials={choices} multiple={wizard.type === "subject"} selected={wizard.selected} query={wizard.query} onQuery={(value) => dispatch({ key: "query", value })} onToggle={(id) => dispatch({ type: "toggle", id })} /> : <section className="rm-empty-small">Upload tài liệu đầu tiên để Nova tạo lộ trình cho bạn.</section>}</>}</>}
      {wizard.step === 2 && <><div className="rm-goal-list">{GOALS.map((goal) => <button key={goal} className={wizard.goals.includes(goal) ? "is-selected" : ""} onClick={() => dispatch({ type: "goal", value: goal })}>{goal}</button>)}</div><div className="rm-time-grid"><label>Số tuần<input type="number" min="1" max="49" step="1" inputMode="numeric" value={wizard.weeks} onKeyDown={(event) => { if ([".", ",", "e", "E", "+", "-"].includes(event.key)) event.preventDefault(); }} onChange={(event) => /^\d*$/.test(event.target.value) && dispatch({ key: "weeks", value: event.target.value })} /></label><label>Giờ/ngày<input type="number" min="1" max="24" step="1" inputMode="numeric" value={wizard.hoursPerDay} onKeyDown={(event) => { if ([".", ",", "e", "E", "+", "-"].includes(event.key)) event.preventDefault(); }} onChange={(event) => /^\d*$/.test(event.target.value) && dispatch({ key: "hoursPerDay", value: event.target.value })} /></label><label>Ngày/tuần<input type="number" min="1" max="7" step="1" inputMode="numeric" value={wizard.daysPerWeek} onKeyDown={(event) => { if ([".", ",", "e", "E", "+", "-"].includes(event.key)) event.preventDefault(); }} onChange={(event) => /^\d*$/.test(event.target.value) && dispatch({ key: "daysPerWeek", value: event.target.value })} /></label></div></>}
    </div>{wizard.error && <p className="rm-error">{wizard.error}</p>}<footer><button className="btn btn-outline" onClick={() => wizard.step ? dispatch({ key: "step", value: wizard.step - 1 }) : setWizardOpen(false)}>Quay lại</button><button className="btn btn-primary" onClick={next}>{wizard.step === 2 ? "Tạo lộ trình" : "Tiếp tục"}<ArrowRightIcon /></button></footer></>}</section></div>}
  </main>;
}
